In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [9]:
df = pd.read_csv('train_data.csv')
X_test = pd.read_csv('test_data.csv')

In [31]:
df[df.final_price < 400].head(20)

,row_ID,vehicle_manufacturer,vehicle_model,vehicle_category,current_mileage,vehicle_year,vehicle_gearbox_type,doors_cnt,wheels,vehicle_color,vehicle_interior_color,car_vin,car_leather_interior,deal_type,final_price
5,5,MITSUBISHI,Delica,Jeep,149000,2003,Automatic,4/5,Right-hand drive,Silver,Black,NaN,0,For Sale,20.0
12,12,LEXUS,GX 470,Jeep,252890,2008,Automatic,4/5,Left wheel,Red,NaN,JTJBT20X780149121,1,For Sale,20.0
24,24,BMW,X5,Jeep,296395,2012,Automatic,4/5,Left wheel,Grey,NaN,5UXZW0C57CL664603,1,For Sale,50.0
26,26,TOYOTA,Camry,Sedan,130478,2014,Automatic,4/5,Left wheel,White,Black,4T1BD1FK3EU107695,1,For Sale,275.0
28,28,TOYOTA,Highlander,Jeep,225464,2012,Automatic,4/5,Left wheel,NaN,Black,JTEDC3EH1C2004166,1,For Sale,250.0
31,31,TOYOTA,Camry,Sedan,314373,2012,Automatic,4/5,Left wheel,Grey,Black,4T1BD1FK2CU027785,1,For Sale,125.0
37,37,CHEVROLET,Volt,Hatchback,0,2013,Automatic,4/5,Left wheel,Grey,NaN,1G1RH6E40DU104154,1,For Sale,100.0
40,40,VOLKSWAGEN,Jetta,Sedan,162987,2012,Automatic,4/5,Left wheel,Grey,NaN,3VWDX7AJ9CM077073,1,For Sale,125.0
52,52,CHEVROLET,1500,Jeep,145896,2017,Automatic,4/5,Left wheel,White,Black,NaN,1,For Sale,150.0
54,54,LEXUS,CT 200h,Hatchback,226666,2012,Automatic,4/5,Left wheel,Black,NaN,JTHKD5BH6C2081249,1,For Sale,225.0
75,75,TOYOTA,Prius,Hatchback,169301,2013,Automatic,4/5,Left wheel,White,Black,JTDKN3DU2D5580904,1,For Sale,50.0
77,77,SUBARU,Forester,Jeep,203730,2012,Automatic,4/5,Left wheel,Blue,NaN,JF2SHAEC5CH451586,1,For Sale,150.0
89,89,TOYOTA,Prius,Hatchback,418667,2012,Automatic,4/5,Left wheel,White,Black,NaN,1,For Sale,100.0
90,90,MERCEDES-BENZ,E 350,Sedan,229904,2010,Automatic,4/5,Left wheel,Black,NaN,WDDHF8HB7AA193979,1,For Sale,150.0
94,94,HYUNDAI,Sonata,Sedan,224349,2011,Automatic,4/5,Left wheel,Grey,NaN,KMHEC4A49BA004756,1,For Sale,80.0
97,97,HONDA,FIT,Hatchback,65000,2007,Automatic,4/5,Right-hand drive,Silver,Grey,NaN,0,For Rent,14.0
98,98,FORD,Escape,Sedan,324594,2008,Automatic,4/5,Left wheel,Silver,NaN,1FMCU02Z48KE62232,1,For Sale,150.0
109,109,MERCEDES-BENZ,E 350,Sedan,101424,2014,Automatic,4/5,Left wheel,Grey,NaN,WDDHF9CB6EA909287,1,For Sale,200.0
112,112,TOYOTA,Highlander,Jeep,260053,2008,Automatic,4/5,Left wheel,Silver,Black,JTEEW41A082007383,1,For Sale,175.0
114,114,ACURA,TL,Sedan,162453,2010,Automatic,4/5,Left wheel,Silver,Black,NaN,1,For Sale,100.0

In [22]:
df[df.deal_type == 'For Sale'].final_price.mean()

6119.694809728849

In [23]:
df[df.deal_type == 'For Rent'].final_price.mean()

233.3264331210191